import Foundation

/// Static, bundled seed content for every NumberTwo feature.
///
/// In a shipping app this would come from a JSON catalog / remote API; for the
/// prototype it is hard-coded so the native apps have something real to show
/// and drill immediately after launch.
public enum SeedData {

    // MARK: - Conjugador (verb drill)

    /// 21 high-frequency Spanish verbs, each fully conjugated across the four
    /// drilled tenses (present, preterite, imperfect, future) and six persons.
    /// Forms are ordered `[yo, tú, él/ella/usted, nosotros, vosotros, ellos]`.
    public static let verbs: [SpanishVerb] = [
        // MARK: Regular -ar
        SpanishVerb(inf: "hablar", en: "to speak",
            present:  ["hablo", "hablas", "habla", "hablamos", "habláis", "hablan"],
            preterite: ["hablé", "hablaste", "habló", "hablamos", "hablasteis", "hablaron"],
            imperfect: ["hablaba", "hablabas", "hablaba", "hablábamos", "hablabais", "hablaban"],
            future:    ["hablaré", "hablarás", "hablará", "hablaremos", "hablaréis", "hablarán"]),
        SpanishVerb(inf: "comprar", en: "to buy",
            present:  ["compro", "compras", "compra", "compramos", "compráis", "compran"],
            preterite: ["compré", "compraste", "compró", "compramos", "comprasteis", "compraron"],
            imperfect: ["compraba", "comprabas", "compraba", "comprábamos", "comprabais", "compraban"],
            future:    ["compraré", "comprarás", "comprará", "compraremos", "compraréis", "comprarán"]),
        SpanishVerb(inf: "estudiar", en: "to study",
            present:  ["estudio", "estudias", "estudia", "estudiamos", "estudiáis", "estudian"],
            preterite: ["estudié", "estudiaste", "estudió", "estudiamos", "estudiasteis", "estudiaron"],
            imperfect: ["estudiaba", "estudiabas", "estudiaba", "estudiábamos", "estudiabais", "estudiaban"],
            future:    ["estudiaré", "estudiarás", "estudiará", "estudiaremos", "estudiaréis", "estudiarán"]),
        SpanishVerb(inf: "trabajar", en: "to work",
            present:  ["trabajo", "trabajas", "trabaja", "trabajamos", "trabajáis", "trabajan"],
            preterite: ["trabajé", "trabajaste", "trabajó", "trabajamos", "trabajasteis", "trabajaron"],
            imperfect: ["trabajaba", "trabajabas", "trabajaba", "trabajábamos", "trabajabais", "trabajaban"],
            future:    ["trabajaré", "trabajarás", "trabajará", "trabajaremos", "trabajaréis", "trabajarán"]),
        SpanishVerb(inf: "usar", en: "to use",
            present:  ["uso", "usas", "usa", "usamos", "usáis", "usan"],
            preterite: ["usé", "usaste", "usó", "usamos", "usasteis", "usaron"],
            imperfect: ["usaba", "usabas", "usaba", "usábamos", "usabais", "usaban"],
            future:    ["usaré", "usarás", "usará", "usaremos", "usaréis", "usarán"]),

        // MARK: Regular -er
        SpanishVerb(inf: "comer", en: "to eat",
            present:  ["como", "comes", "come", "comemos", "coméis", "comen"],
            preterite: ["comí", "comiste", "comió", "comimos", "comisteis", "comieron"],
            imperfect: ["comía", "comías", "comía", "comíamos", "comíais", "comían"],
            future:    ["comeré", "comerás", "comerá", "comeremos", "comeréis", "comerán"]),
        SpanishVerb(inf: "beber", en: "to drink",
            present:  ["bebo", "bebes", "bebe", "bebemos", "bebéis", "beben"],
            preterite: ["bebí", "bebiste", "bebió", "bebimos", "bebisteis", "bebieron"],
            imperfect: ["bebía", "bebías", "bebía", "bebíamos", "bebíais", "bebían"],
            future:    ["beberé", "beberás", "beberá", "beremos", "beberéis", "beberán"]),
        SpanishVerb(inf: "aprender", en: "to learn",
            present:  ["aprendo", "aprendes", "aprende", "aprendemos", "aprendéis", "aprenden"],
            preterite: ["aprendí", "aprendiste", "aprendió", "aprendimos", "aprendisteis", "aprendieron"],
            imperfect: ["aprendía", "aprendías", "aprendía", "aprendíamos", "aprendíais", "aprendían"],
            future:    ["aprenderé", "aprenderás", "aprenderá", "aprenderemos", "aprenderéis", "aprenderán"]),
        SpanishVerb(inf: "vender", en: "to sell",
            present:  ["vendo", "vendes", "vende", "vendemos", "vendéis", "venden"],
            preterite: ["vendí", "vendiste", "vendió", "vendimos", "vendisteis", "vendieron"],
            imperfect: ["vendía", "vendías", "vendía", "vendíamos", "vendíais", "vendían"],
            future:    ["venderé", "venderás", "venderá", "venderemos", "venderéis", "venderán"]),

        // MARK: Regular -ir
        SpanishVerb(inf: "vivir", en: "to live",
            present:  ["vivo", "vives", "vive", "vivimos", "vivís", "viven"],
            preterite: ["viví", "viviste", "vivió", "vivimos", "vivisteis", "vivieron"],
            imperfect: ["vivía", "vivías", "vivía", "vivíamos", "vivíais", "vivían"],
            future:    ["viviré", "vivirás", "vivirá", "viviremos", "viviréis", "vivirán"]),
        SpanishVerb(inf: "abrir", en: "to open",
            present:  ["abro", "abres", "abre", "abrimos", "abrís", "abren"],
            preterite: ["abrí", "abriste", "abrió", "abrimos", "abristeis", "abrieron"],
            imperfect: ["abría", "abrías", "abría", "abríamos", "abríais", "abrían"],
            future:    ["abriré", "abrirás", "abrirá", "abriremos", "abriréis", "abrirán"]),
        SpanishVerb(inf: "escribir", en: "to write",
            present:  ["escribo", "escribes", "escribe", "escribimos", "escribís", "escriben"],
            preterite: ["escribí", "escribiste", "escribió", "escribimos", "escribisteis", "escribieron"],
            imperfect: ["escribía", "escribías", "escribía", "escribíamos", "escribíais", "escribían"],
            future:    ["escribiré", "escribirás", "escribirá", "escribiremos", "escribiréis", "escribirán"]),

        // MARK: Irregular
        SpanishVerb(inf: "ser", en: "to be",
            present:  ["soy", "eres", "es", "somos", "sois", "son"],
            preterite: ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
            imperfect: ["era", "eras", "era", "éramos", "erais", "eran"],
            future:    ["seré", "serás", "será", "seremos", "seréis", "serán"]),
        SpanishVerb(inf: "estar", en: "to be (temp.)",
            present:  ["estoy", "estás", "está", "estamos", "estáis", "están"],
            preterite: ["estuve", "estuviste", "estuvo", "estuvimos", "estuvisteis", "estuvieron"],
            imperfect: ["estaba", "estabas", "estaba", "estábamos", "estabais", "estaban"],
            future:    ["estaré", "estarás", "estará", "estaremos", "estaréis", "estarán"]),
        SpanishVerb(inf: "tener", en: "to have",
            present:  ["tengo", "tienes", "tiene", "tenemos", "tenéis", "tienen"],
            preterite: ["tuve", "tuviste", "tuvo", "tuvimos", "tuvisteis", "tuvieron"],
            imperfect: ["tenía", "tenías", "tenía", "teníamos", "teníais", "tenían"],
            future:    ["tendré", "tendrás", "tendrá", "tendremos", "tendréis", "tendrán"]),
        SpanishVerb(inf: "ir", en: "to go",
            present:  ["voy", "vas", "va", "vamos", "vais", "van"],
            preterite: ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
            imperfect: ["iba", "ibas", "iba", "íbamos", "ibais", "iban"],
            future:    ["iré", "irás", "irá", "iremos", "iréis", "irán"]),
        SpanishVerb(inf: "hacer", en: "to do / make",
            present:  ["hago", "haces", "hace", "hacemos", "hacéis", "hacen"],
            preterite: ["hice", "hiciste", "hizo", "hicimos", "hicisteis", "hicieron"],
            imperfect: ["hacía", "hacías", "hacía", "hacíamos", "hacíais", "hacían"],
            future:    ["haré", "harás", "hará", "haremos", "haréis", "harán"]),
        SpanishVerb(inf: "querer", en: "to want / love",
            present:  ["quiero", "quieres", "quiere", "queremos", "queréis", "quieren"],
            preterite: ["quise", "quisiste", "quiso", "quisimos", "quisisteis", "quisieron"],
            imperfect: ["quería", "querías", "quería", "queríamos", "queríais", "querían"],
            future:    ["querré", "querrás", "querrá", "querremos", "querréis", "querrán"]),
        SpanishVerb(inf: "poder", en: "to be able",
            present:  ["puedo", "puedes", "puede", "podemos", "podéis", "pueden"],
            preterite: ["pude", "pudiste", "pudo", "pudimos", "pudisteis", "pudieron"],
            imperfect: ["podía", "podías", "podía", "podíamos", "podíais", "podían"],
            future:    ["podré", "podrás", "podrá", "podremos", "podréis", "podrán"]),
        SpanishVerb(inf: "decir", en: "to say / tell",
            present:  ["digo", "dices", "dice", "decimos", "decís", "dicen"],
            preterite: ["dije", "dijiste", "dijo", "dijimos", "dijisteis", "dijeron"],
            imperfect: ["decía", "decías", "decía", "decíamos", "decíais", "decían"],
            future:    ["diré", "dirás", "dirá", "diremos", "diréis", "dirán"]),
        SpanishVerb(inf: "ver", en: "to see",
            present:  ["veo", "ves", "ve", "vemos", "veis", "ven"],
            preterite: ["vi", "viste", "vio", "vimos", "visteis", "vieron"],
            imperfect: ["veía", "veías", "veía", "veíamos", "veíais", "veían"],
            future:    ["veré", "verás", "verá", "veremos", "veréis", "verán"]),
    ]

    // MARK: - LingoBox (flashcards)

    public static let flashcards: [Flashcard] = [
        Flashcard(id: "f1",  es: "el agua",      en: "water",        example: "Quiero un vaso de agua."),
        Flashcard(id: "f2",  es: "la comida",    en: "food",         example: "La comida está deliciosa."),
        Flashcard(id: "f3",  es: "el café",      en: "coffee",       example: "Tomo café por las mañanas."),
        Flashcard(id: "f4",  es: "el pan",       en: "bread",        example: "Compré pan fresco."),
        Flashcard(id: "f5",  es: "la manzana",   en: "apple",        example: "Me como una manzana."),
        Flashcard(id: "f6",  es: "el tren",      en: "train",        example: "El tren llega a las ocho."),
        Flashcard(id: "f7",  es: "el aeropuerto", en: "airport",     example: "Vamos al aeropuerto."),
        Flashcard(id: "f8",  es: "el hotel",     en: "hotel",        example: "Reservé un hotel."),
        Flashcard(id: "f9",  es: "el pasaporte", en: "passport",     example: "No encuentro mi pasaporte."),
        Flashcard(id: "f10", es: "la playa",     en: "beach",        example: "Pasamos el día en la playa."),
        Flashcard(id: "f11", es: "hola",         en: "hello",        example: "¡Hola! ¿Cómo estás?"),
        Flashcard(id: "f12", es: "gracias",      en: "thank you",    example: "Muchas gracias."),
        Flashcard(id: "f13", es: "por favor",    en: "please",       example: "Un café, por favor."),
        Flashcard(id: "f14", es: "buenos días",  en: "good morning", example: "Buenos días, señor."),
        Flashcard(id: "f15", es: "adiós",        en: "goodbye",      example: "Adiós, hasta mañana."),
        Flashcard(id: "f16", es: "el gato",      en: "cat",          example: "El gato duerme."),
        Flashcard(id: "f17", es: "el perro",     en: "dog",          example: "El perro corre."),
        Flashcard(id: "f18", es: "la casa",      en: "house",        example: "Mi casa es pequeña."),
        Flashcard(id: "f19", es: "el libro",     en: "book",         example: "Leo un libro."),
        Flashcard(id: "f20", es: "la ciudad",    en: "city",         example: "Madrid es una ciudad grande."),
    ]

    // MARK: - Hola (mini-lessons)

    public static let lessons: [Lesson] = [
        Lesson(
            id: "l-basics",
            title: "Greetings",
            emoji: "👋",
            exercises: [
                .choice(id: "g1", prompt: "How do you say 'hello'?",
                        options: ["Hola", "Adiós", "Gracias", "Por favor"], answer: "Hola",
                        hint: "It is the most common greeting."),
                .tap(id: "g2", prompt: "Build: 'Good morning, friend.'",
                     source: "Buenos días, amigo.",
                     bank: ["Buenos", "días,", "amigo.", "gracias"],
                     answer: ["Buenos", "días,", "amigo."]),
                .match(id: "g3", prompt: "Match the words",
                       pairs: [
                        MatchPair(es: "gracias", en: "thank you"),
                        MatchPair(es: "hola", en: "hello"),
                        MatchPair(es: "adiós", en: "goodbye"),
                       ]),
                .listen(id: "g4", prompt: "Which phrase did you hear?",
                        audioText: "Muchas gracias", options: ["Muchas gracias", "Buenas noches", "Por favor"],
                        answer: "Muchas gracias"),
            ]),
        Lesson(
            id: "l-food",
            title: "Food",
            emoji: "🍎",
            exercises: [
                .choice(id: "f1", prompt: "What is 'el agua'?",
                        options: ["water", "bread", "coffee", "milk"], answer: "water",
                        hint: "It is something you drink."),
                .tap(id: "f2", prompt: "Build: 'I want coffee, please.'",
                     source: "Quiero café, por favor.",
                     bank: ["Quiero", "café,", "por", "favor.", "agua"],
                     answer: ["Quiero", "café,", "por", "favor."]),
                .match(id: "f3", prompt: "Match the food",
                       pairs: [
                        MatchPair(es: "el pan", en: "bread"),
                        MatchPair(es: "la manzana", en: "apple"),
                        MatchPair(es: "el café", en: "coffee"),
                       ]),
            ]),
        Lesson(
            id: "l-travel",
            title: "Travel",
            emoji: "✈️",
            exercises: [
                .choice(id: "t1", prompt: "What is 'el aeropuerto'?",
                        options: ["airport", "hotel", "train", "beach"], answer: "airport",
                        hint: "Where planes take off."),
                .tap(id: "t2", prompt: "Build: 'We go to the hotel.'",
                     source: "Vamos al hotel.",
                     bank: ["Vamos", "al", "hotel.", "casa"],
                     answer: ["Vamos", "al", "hotel."]),
                .listen(id: "t3", prompt: "Which phrase did you hear?",
                        audioText: "El tren llega tarde",
                        options: ["El tren llega tarde", "El café está frío", "La casa es grande"],
                        answer: "El tren llega tarde"),
            ]),
    ]

    // MARK: - Cuentos (graded stories)

    public static let stories: [Story] = [
        Story(id: "s-cat", title: "El gato y el sol", level: "A1",
              sentences: [
                StorySentence(es: "El gato es pequeño.", en: "The cat is small."),
                StorySentence(es: "El gato duerme.", en: "The cat sleeps."),
                StorySentence(es: "El sol brilla.", en: "The sun shines."),
                StorySentence(es: "El gato abre los ojos.", en: "The cat opens its eyes."),
                StorySentence(es: "El gato mira el sol.", en: "The cat looks at the sun."),
              ]),
        Story(id: "s-coffee", title: "Un café por la mañana", level: "A1",
              sentences: [
                StorySentence(es: "Es de mañana.", en: "It is morning."),
                StorySentence(es: "Yo tomo un café.", en: "I drink a coffee."),
                StorySentence(es: "El café está caliente.", en: "The coffee is hot."),
                StorySentence(es: "El café es delicioso.", en: "The coffee is delicious."),
                StorySentence(es: "Yo sonrío.", en: "I smile."),
              ]),
        Story(id: "s-train", title: "El viaje en tren", level: "A2",
              sentences: [
                StorySentence(es: "Hoy viajo en tren.", en: "Today I travel by train."),
                StorySentence(es: "El tren es rápido.", en: "The train is fast."),
                StorySentence(es: "Veo la ciudad por la ventana.", en: "I see the city through the window."),
                StorySentence(es: "Llego al aeropuerto.", en: "I arrive at the airport."),
                StorySentence(es: "Estoy feliz.", en: "I am happy."),
              ]),
    ]

    // MARK: - Habla (offline conversation coach)

    public static let scenarios: [Scenario] = [
        Scenario(
            id: "s-coffee",
            title: "Ordering Coffee",
            subtitle: "At a café in Madrid",
            level: "A1",
            icon: "☕️",
            vocab: [
                ScenarioVocab(es: "un café", en: "a coffee"),
                ScenarioVocab(es: "por favor", en: "please"),
                ScenarioVocab(es: "gracias", en: "thank you"),
                ScenarioVocab(es: "la cuenta", en: "the bill"),
            ],
            turns: [
                ScenarioTurn(botEs: "¡Hola! ¿Qué quieres tomar?",
                              botEn: "Hi! What would you like to drink?",
                              expects: ["un café", "quiero un café", "café"],
                              hintEs: "Try: 'Un café, por favor.'",
                              coachEn: "Great start — 'un café' means 'a coffee'."),
                ScenarioTurn(botEs: "Muy bien. ¿Algo más?",
                              botEn: "Very good. Anything else?",
                              expects: ["no, gracias", "nada más", "no"],
                              hintEs: "Try: 'No, gracias.'",
                              coachEn: "Perfect — 'No, gracias' politely ends the order."),
                ScenarioTurn(botEs: "Son dos euros. Aquí tiene.",
                              botEn: "That's two euros. Here you go.",
                              expects: ["gracias", "muchas gracias"],
                              hintEs: "Try: 'Muchas gracias.'",
                              coachEn: "Excellent — you closed the conversation naturally."),
            ],
            introEs: "Vamos a pedir un café.",
            introEn: "Let's order a coffee.",
            outroEs: "¡Buen trabajo!",
            outroEn: "Nice work!"),

        Scenario(
            id: "s-train",
            title: "Buying a Train Ticket",
            subtitle: "At the station",
            level: "A2",
            icon: "🚆",
            vocab: [
                ScenarioVocab(es: "el tren", en: "the train"),
                ScenarioVocab(es: "un billete", en: "a ticket"),
                ScenarioVocab(es: "a Barcelona", en: "to Barcelona"),
                ScenarioVocab(es: "cuánto cuesta", en: "how much does it cost"),
            ],
            turns: [
                ScenarioTurn(botEs: "Buenos días. ¿Adónde vas?",
                              botEn: "Good morning. Where are you going?",
                              expects: ["a Barcelona", "voy a Barcelona"],
                              hintEs: "Try: 'Voy a Barcelona.'",
                              coachEn: "'Voy a…' means 'I'm going to…'."),
                ScenarioTurn(botEs: "¿Un billete? ¿Ida o vuelta?",
                              botEn: "One ticket? One-way or round-trip?",
                              expects: ["ida", "ida y vuelta", "un billete"],
                              hintEs: "Try: 'Ida, por favor.'",
                              coachEn: "'Ida' is one-way, 'ida y vuelta' is round-trip."),
                ScenarioTurn(botEs: "Son quince euros.",
                              botEn: "That's fifteen euros.",
                              expects: ["gracias", "aquí tiene", "un momento"],
                              hintEs: "Try: 'Aquí tiene.'",
                              coachEn: "You paid — 'Aquí tiene' hands over the money."),
            ],
            introEs: "Compras un billete de tren.",
            introEn: "You buy a train ticket.",
            outroEs: "¡Perfecto!",
            outroEn: "Perfect!"),

        Scenario(
            id: "s-hotel",
            title: "Checking into a Hotel",
            subtitle: "At reception",
            level: "A2",
            icon: "🏨",
            vocab: [
                ScenarioVocab(es: "una habitación", en: "a room"),
                ScenarioVocab(es: "una noche", en: "one night"),
                ScenarioVocab(es: "tengo una reserva", en: "I have a reservation"),
                ScenarioVocab(es: "el pasaporte", en: "the passport"),
            ],
            turns: [
                ScenarioTurn(botEs: "Buenas tardes. ¿En qué le ayudo?",
                              botEn: "Good afternoon. How can I help you?",
                              expects: ["tengo una reserva", "una habitación"],
                              hintEs: "Try: 'Tengo una reserva.'",
                              coachEn: "'Tengo una reserva' = 'I have a reservation'."),
                ScenarioTurn(botEs: "¿Su nombre, por favor?",
                              botEn: "Your name, please?",
                              expects: ["soy", "me llamo"],
                              hintEs: "Try: 'Me llamo Ana.'",
                              coachEn: "'Me llamo…' introduces your name."),
                ScenarioTurn(botEs: "Gracias. Aquí está su llave.",
                              botEn: "Thanks. Here is your key.",
                              expects: ["gracias", "muchas gracias"],
                              hintEs: "Try: 'Muchas gracias.'",
                              coachEn: "Done — you checked in like a local."),
            ],
            introEs: "Llegas al hotel.",
            introEn: "You arrive at the hotel.",
            outroEs: "¡Bienvenido!",
            outroEn: "Welcome!"),
    ]
}
